import Flutter
import UIKit

/// iOS implementation of the levalgo_battery_status plugin.
///
/// A single instance serves both channels declared by the Dart layer: a
/// `FlutterMethodChannel` for one-off queries, hence `FlutterPlugin`, and a
/// `FlutterEventChannel` for the stream of state changes, hence
/// `FlutterStreamHandler`.
///
/// ## Why the class is `public` and derives from `NSObject`
///
/// `GeneratedPluginRegistrant.m` is generated by Flutter in Objective-C, and
/// does this:
///
/// ```objc
/// [LevalgoBatteryStatusPlugin registerWithRegistrar:...];
/// ```
///
/// For that message to resolve against a Swift class, both conditions must
/// hold at once:
///
///  - **`NSObject`**: only classes deriving from `NSObject` are exposed to the
///    Objective-C runtime. Without that inheritance the class exists for Swift
///    but not for the registrant, which looks it up by name at runtime.
///  - **`public`**: the registrant lives in the app's module, not the
///    plugin's. With `internal` visibility the class never crosses that
///    boundary.
///
/// Because it derives from `NSObject`, Swift exposes `register(with:)` as
/// `registerWithRegistrar:` automatically, which is exactly the selector the
/// registrant sends.
///
/// Dropping either one compiles without error and fails at runtime, surfacing
/// as a `MissingPluginException` on the Dart side. It is a well-known and
/// annoying class of bug precisely because the compiler stays silent.
public class LevalgoBatteryStatusPlugin: NSObject, FlutterPlugin,
  FlutterStreamHandler
{
  /// Channel names. These must match, character for character, the ones
  /// declared in `levalgo_battery_status_method_channel.dart`.
  private static let methodChannelName = "levalgo_battery_status"
  private static let eventChannelName = "levalgo_battery_status/state"

  /// State identifiers understood by the Dart layer. They travel as strings
  /// so the contract does not depend on an enum's ordering.
  private enum StateIdentifier {
    static let full = "full"
    static let charging = "charging"
    static let discharging = "discharging"
    static let unknown = "unknown"
  }

  private let battery: BatteryProviding
  private let notificationCenter: NotificationCenter

  private var eventSink: FlutterEventSink?
  private var observer: NSObjectProtocol?

  /// Creates the plugin.
  ///
  /// Both dependencies have defaults, so production code constructs it with
  /// `LevalgoBatteryStatusPlugin()` while tests pass in doubles.
  public init(
    battery: BatteryProviding = DeviceBattery(),
    notificationCenter: NotificationCenter = .default
  ) {
    self.battery = battery
    self.notificationCenter = notificationCenter
    super.init()
  }

  deinit {
    // Safety net in case the instance dies without Dart having cancelled the
    // subscription.
    stopObserving()
  }

  // MARK: - Registration

  public static func register(with registrar: FlutterPluginRegistrar) {
    let instance = LevalgoBatteryStatusPlugin()

    let methodChannel = FlutterMethodChannel(
      name: methodChannelName,
      binaryMessenger: registrar.messenger()
    )
    registrar.addMethodCallDelegate(instance, channel: methodChannel)

    let eventChannel = FlutterEventChannel(
      name: eventChannelName,
      binaryMessenger: registrar.messenger()
    )
    eventChannel.setStreamHandler(instance)
  }

  // MARK: - FlutterPlugin

  public func handle(
    _ call: FlutterMethodCall,
    result: @escaping FlutterResult
  ) {
    switch call.method {
    case "getBatteryLevel":
      result(batteryLevelResult())
    case "getBatteryState":
      result(currentStateIdentifier())
    default:
      // Flutter's contract: anything unrecognised is answered with this
      // sentinel, which reaches Dart as MissingPluginException.
      result(FlutterMethodNotImplemented)
    }
  }

  // MARK: - FlutterStreamHandler

  public func onListen(
    withArguments arguments: Any?,
    eventSink events: @escaping FlutterEventSink
  ) -> FlutterError? {
    eventSink = events
    startObserving()
    // Returning nil means the subscription was accepted.
    return nil
  }

  public func onCancel(withArguments arguments: Any?) -> FlutterError? {
    stopObserving()
    eventSink = nil
    return nil
  }

  // MARK: - Device readings

  /// Returns the percentage, or a `FlutterError` when it is unavailable.
  private func batteryLevelResult() -> Any {
    battery.enableMonitoring()

    let level = battery.level
    guard level >= 0 else {
      return FlutterError(
        code: "UNAVAILABLE",
        message: """
          The system does not report a battery level. It is never available \
          on the iOS simulator: try a physical device.
          """,
        details: nil
      )
    }

    // Rounding happens here so the native layer already hands over the 0 to
    // 100 integer the public API promises.
    return Int((level * 100).rounded())
  }

  /// Translates `UIDevice.BatteryState` into the identifier Dart expects.
  private func currentStateIdentifier() -> String {
    battery.enableMonitoring()

    switch battery.state {
    case .full: return StateIdentifier.full
    case .charging: return StateIdentifier.charging
    case .unplugged: return StateIdentifier.discharging
    case .unknown: return StateIdentifier.unknown
    // UIDeviceBatteryState comes from Objective-C, so Swift cannot guarantee
    // the list is exhaustive: a future iOS release could add cases.
    // @unknown default forces handling them and makes the compiler warn when
    // a new one appears.
    @unknown default: return StateIdentifier.unknown
    }
  }

  // MARK: - NotificationCenter observer

  private func startObserving() {
    // Idempotent: a second observer would emit every change twice.
    guard observer == nil else { return }

    battery.enableMonitoring()

    // `self` is captured weakly on purpose: the notification center retains
    // the block, and the block would retain the plugin. Without [weak self]
    // that is a cycle keeping it alive long after anyone needs it.
    observer = notificationCenter.addObserver(
      forName: UIDevice.batteryStateDidChangeNotification,
      object: nil,
      queue: .main
    ) { [weak self] _ in
      // The notification does not carry the new state, it only announces that
      // it changed, so it has to be read again.
      self?.emitCurrentState()
    }
  }

  private func stopObserving() {
    guard let observer else { return }
    notificationCenter.removeObserver(observer)
    self.observer = nil
  }

  private func emitCurrentState() {
    // In the Objective-C version this line needed a manual nil check, because
    // invoking a nil block crashes the process. In Swift, optional chaining
    // makes it impossible to forget.
    eventSink?(currentStateIdentifier())
  }
}
